In [2]:
# importing packages

import numpy as np
import pandas as pd

### Q1. Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [13]:
def alex(input_array,n_columns_order):
    
    x=np.array(input_array)

    print(f"The output matrix is: \n{np.column_stack([x**(n_columns_order-1-i) for i in range(n_columns_order)])}")
    
alex([1,2,3,4,5],5)

The output matrix is: 
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


### Q2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 

The moving average sequence has n-k+1 elements as shown below. 

The moving averages with k=4 of a ten-value sequence (n=10) is shown below 

i 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 y1 25 = (10+20+30+40)/4 y2 35 = (20+30+40+50)/4 y3 45 = (30+40+50+60)/4 y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4 

Thus, the moving average sequence has n-k+1=10-4+1=7 values. 

Question: Write a function to find moving average in an array over a window: 

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [40]:
def moving_av(input_list,time_period):

    y=[]
    
    try:

        [y.append(np.round(np.sum(input_list[i:i+time_period])/time_period,3)) for i in range(len(input_list)-time_period+1)]
        
    except:
        
        print('Please enter a positive moving average time period and non-zero')
    
    print(f'The output of the moving average for time period {time_period} is: \n {y}')
    
moving_av([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)
    

The output of the moving average for time period 3 is: 
 [5.0, 4.667, 5.667, 6.667, 9.667, 28.667, 49.333, 72.667, 84.0, 93.333, 116.333]
